// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgkoomwiuwdcytwsyvaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZna29vbXdpdXdkY3l0d3N5dmFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NDYwNzYsImV4cCI6MjA3MDMyMjA3Nn0.SpfzXMTpcFMvl5rMp7BWaixLZFm4F2Cs_3bBWSGeq_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});